### ISSUE TITLE
Error in `read_wave_info`: failure writing uncompressed data

### ISSUE THREAD

**Issue by desh2608** [csukuangfj/kaldi_native_io#23]
I am trying to use Lhotse's `load_kaldi_data_dir` to convert a Kaldi WSJ data directory to Lhotse manifests. The `wav.scp` file has entries of the form:
```
440c0401 /export/b16/draj/kaldi/egs/wsj/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav /export/corpora5/LDC/LDC93S6B/11-14.1/wsj0/si_et_20/440/440c0401.wv1 |
440c0402 /export/b16/draj/kaldi/egs/wsj/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav /export/corpora5/LDC/LDC93S6B/11-14.1/wsj0/si_et_20/440/440c0402.wv1 |
440c0403 /export/b16/draj/kaldi/egs/wsj/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav /export/corpora5/LDC/LDC93S6B/11-14.1/wsj0/si_et_20/440/440c0403.wv1 |
```

The conversion fails at [this](https://github.com/lhotse-speech/lhotse/blob/b5cd8e1c97d57458645359e44c1b4525f704c22e/lhotse/kaldi.py#L38) line because of error in the `read_wave_info` function:
```
failure writing uncompressed data from /export/corpora5/LDC/LDC93S6B/11-14.1/wsj0/si_et_20/440/440c0401.wv1 to (null)
```

Is this a bug or am I doing something wrong?

**Comment by csukuangfj** [comment]
Sorry, I missed this issue.

The error
> failure writing uncompressed data from /export/corpora5/LDC/LDC93S6B/11-14.1/wsj0/si_et_20/440/440c0401.wv1 to (null)

is from `sph2pipe`
![Screen Shot 2022-04-12 at 23 41 35](https://user-images.githubusercontent.com/5284924/163001215-2b7c2a4e-0a38-4b57-8362-24de37ebaf9f.png)

Looks like there is an error in executing
```bash
/export/b16/draj/kaldi/egs/wsj/s5/../../../tools/sph2pipe_v2.5/sph2pipe -f wav /export/corpora5/LDC/LDC93S6B/11-14.1/wsj0/si_et_20/440/440c0401.wv1
```

Does the above command work if you run it from the command line?

**Comment by desh2608** [comment]
Yes, it seems to be working fine when run directly from the command line.

**Comment by csukuangfj** [comment]
Fixed in https://github.com/csukuangfj/kaldi_native_io/pull/24

Please try kaldi_native_io v1.6. 

Feel free to re-open it if it is not fixed.
